---
{% set output = "az vmss nic list --resource-group ppw-dev-compute-rg --vmss-name ppw-dev-compute-vmss  --query '[].ipConfigurations[].privateIPAddress' --output tsv"  | shell -%}
{%- set cluster_ips = output.splitlines() | sort -%}

all:
  vars:
    ansible_python_interpreter: "/usr/bin/python3"

  children:
    control:
      hosts:
        127.0.0.1:

    master:
      hosts:
        {% if cluster_ips -%}
          {{ cluster_ips[0] }}:
        {%- endif %}

    workers:
      hosts:
        {% for ip in cluster_ips[1:] -%}
          {{ ip }}:
        {% endfor %}
    cluster:
      hosts:
        {% for ip in cluster_ips -%}
          {{ ip }}:
        {% endfor %}

