---
- name: "Cluster Common Setup"
  hosts: "all"
  gather_facts: false

  vars:
    netdata_room_uuid: "65ab7582-6c5f-480b-bee4-237299b92f93"

  tasks:

    - name: "Wait for cloud-init to finish"
      become: false
      ansible.builtin.shell: "cloud-init status --wait"

    - name: "Add `azuser` to `rdma` group"
      become: true
      ansible.builtin.user:
        name: "azuser"
        groups: "rdma"
        append: true

    - name: "Mount scratch disk"
      become: true
      ansible.builtin.script: "setup_scratch.sh"
      args:
        creates: "/scratch"

    - name: "Install netdata"
      become: true
      ansible.builtin.script: "setup_netdata.sh {{ netdata_room_uuid }}"
      args:
        creates: "/etc/netdata/netdata.conf"

    - name: "Install schism"
      vars:
        env_name: "schism_env"
      ansible.builtin.shell: |
        /usr/bin/bash -lic '
        source init_conda
        micromamba create --yes --quiet --name {{ env_name }} "pschism=5.9*=mpi_openmpi*" ucx
        micromamba activate {{ env_name }}
        which schism
        '
      args:
        creates: "/mnt/micromamba/envs/{{ env_name }}"
