---
- name: "Setup Master VM"
  hosts: "master"
  gather_facts: false

  tasks:

    - name: "Install dependencies"
      become: true
      ansible.builtin.apt:
        pkg:
          - "nfs-kernel-server"
        state: "present"
        update_cache: true
        install_recommends: false
        lock_timeout: 60
        cache_valid_time: 3600

    - name: "Update /etc/idmapd.conf"
      become: true
      ansible.builtin.replace:
        path: "/etc/idmapd.conf"
        regexp: "(nobody|nogroup)"
        replace: "azuser"

    - name: "Mount scratch disk"
      become: true
      ansible.builtin.script: "setup_scratch.sh"
      args:
        creates: "/scratch"

    - name: "Create /scratch/shared"
      become: true
      ansible.builtin.file:
        path: "/scratch/shared"
        state: "directory"
        mode: "0755"
        owner: "azuser"
        group: "azuser"

    - name: "Update /etc/exports"
      become: true
      ansible.builtin.lineinfile:
        path: "/etc/exports"
        line: "/scratch/shared    10.10.0.0/16(rw,sync,no_subtree_check)"
        create: false

    - name: "Update exportfs"
      become: true
      ansible.builtin.command: "exportfs -arv"

    - name: "Restart nfs-kernel-server"
      become: true
      ansible.builtin.systemd:
        state: "restarted"
        name: "nfs-kernel-server"

    - name: "Sent notification"
      ansible.builtin.command: "/home/azuser/.local/bin/ntfy send 'Provisioning of MASTER finished: {{ now(utc=True) }}'"
