---
- name: "Setup Worker VM"
  hosts: "all"
  gather_facts: false

  tasks:

    - name: "Install dependencies"
      become: true
      ansible.builtin.apt:
        pkg:
          - "nfs-common"
        state: "present"
        update_cache: true
        install_recommends: false
        lock_timeout: 60
        cache_valid_time: 3600

    - name: "Unmount NFS volume"
      become: true
      ansible.posix.mount:
        src: "{{ hostvars[inventory_hostname]['groups']['master'][0] }}:/scratch/shared"
        path: "/scratch/shared"
        state: "unmounted"

    - name: "Create /scratch/shared"
      become: true
      ansible.builtin.file:
        path: "/scratch/shared"
        state: "directory"
        mode: "0755"
        owner: "azuser"
        group: "azuser"

    - name: "Mount NFS volume"
      become: true
      ansible.posix.mount:
        src: "{{ hostvars[inventory_hostname]['groups']['master'][0] }}:/scratch/shared"
        path: "/scratch/shared"
        opts: "rw,sync,hard"
        state: "mounted"
        fstype: "nfs"

    - name: "Sent notification"
      ansible.builtin.command: "/home/azuser/.local/bin/ntfy send 'Provisioning of WORKER finished: {{ now(utc=True) }}'"
