---
- name: "Common Setup"
  hosts: "all"
  gather_facts: false

  tasks:
    - name: "Install dependencies"
      become: true
      ansible.builtin.apt:
        pkg:
          - "aria2"
          - "bat"
          - "curl"
          - "fd-find"
          - "iperf"
          - "kitty-terminfo"
          - "nfs-common"
          - "nfs-kernel-server"
          - "python3.9"
          - "python3.9-venv"
          - "python3-venv"
          - "qperf"
          - "silversearcher-ag"
          - "stow"
          - "tree"
          - "wget"
        state: "present"
        update_cache: true
        install_recommends: false
        lock_timeout: 60
        cache_valid_time: 3600

    - name: "Setup dotfiles (if necessary)"
      ansible.builtin.script: "setup_dotfiles.sh"
      args:
        creates: "/home/azuser/.dotfiles"

    - name: "Setup SSH (if necessary)"
      ansible.builtin.script: "setup_ssh.sh"
      args:
        creates: "/home/azuser/.ssh/id_rsa"
      tags:
        - "ssh"

    - name: "Setup /mnt"
      become: true
      ansible.builtin.file:
        path: "/mnt"
        owner: "azuser"
        group: "azuser"

    - name: "Setup conda (if necessary)"
      ansible.builtin.script: "setup_conda.sh"
      args:
        creates: "/mnt/mambaforge/envs/schism_env"

    - name: "Setup pipx (if necessary)"
      ansible.builtin.script: "setup_pipx.sh"
      args:
        creates: "/home/azuser/.local/bin/pipx"

    - name: "Setup ntfy (if necessary)"
      ansible.builtin.script: "setup_ntfy.sh"
      ignore_errors: true
      args:
        creates: "/home/azuser/.local/bin/ntfy"

    - name: "Login to azcopy"
      ansible.builtin.command: "azcopy login --identity"
