---
- name: "Common Setup"
  hosts: "all"
  gather_facts: false

  tasks:

    - name: "Install dependencies"
      become: true
      ansible.builtin.apt:
        pkg:
          - "aria2"
          - "bat"
          - "bzip2"
          - "curl"
          - "fd-find"
          - "jq"
          - "kitty-terminfo"
          - "moreutils"
          - "python3.10"
          - "python3.10-venv"
          - "python3-pip"
          - "silversearcher-ag"
          - "stow"
          - "sysstat"
          - "tar"
          - "tree"
          - "wget"
        state: "present"
        update_cache: true
        install_recommends: false
        lock_timeout: 300
        cache_valid_time: 3600

    - name: "Setup dotfiles (if necessary)"
      ansible.builtin.script: "setup_dotfiles.sh"
      args:
        creates: "/home/azuser/.dotfiles"

    - name: "Setup /mnt"
      become: true
      ansible.builtin.file:
        path: "/mnt"
        owner: "azuser"
        group: "azuser"

    - name: "Use /mnt/pip_cache as the cache for pip"
      ansible.builtin.shell: |
        mkdir -p /mnt/cache/pip;
        mkdir -p /home/azuser/.config/pip;
        touch    /home/azuser/.config/pip/pip.conf;
        echo '[global]' >> /home/azuser/.config/pip/pip.conf;
        echo 'cache-dir=/mnt/cache/pip' >> /home/azuser/.config/pip/pip.conf;
      args:
        creates: "/home/azuser/.config/pip/pip.conf"

    - name: "Ensure that MAMBA_ROOT_PREFIX points to /mnt/micromamba"
      ansible.builtin.lineinfile:
        path: "/home/azuser/.bashrc"
        line: "export MAMBA_ROOT_PREFIX=/mnt/micromamba"

    - name: "Setup mamba (if necessary)"
      ansible.builtin.shell: |
        curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj -C ~/.local/bin/ --strip-components=1 bin/micromamba
      args:
        creates: "/home/azuser/.local/bin/micromamba"

    - name: "Setup pipx (if necessary)"
      ansible.builtin.shell: |
        /usr/bin/bash -lic '
          if [ ! -x "$(command -v pipx)" ]; then
            python3.10 -m pip install --no-warn-script-location --user pipx
          fi
        '
      args:
        creates: "/home/azuser/.local/bin/pipx"

    - name: "Setup ntfy (if necessary)"
      ansible.builtin.shell: |
        /usr/bin/bash -lic "
          python3.10 -m pipx install 'git+https://github.com/pmav99/ntfy.git'
          mkdir -p ~/.config/ntfy;
          touch ~/.config/ntfy/ntfy.yml
          echo 'backends:'  >> ~/.config/ntfy/ntfy.yml
          echo '  - \"teams\"' >> ~/.config/ntfy/ntfy.yml
          echo 'teams:' >> ~/.config/ntfy/ntfy.yml
          echo '  webhook_url: \"https://eceuropaeu.webhook.office.com/webhookb2/c30cb985-f82c-4d12-b57b-63e848c7917c@b24c8b06-522c-46fe-9080-70926f8dddb1/IncomingWebhook/f36b00fe4b374316b9405e25980ae4a4/0eb06807-09cd-4dfc-917b-ccc7ef0fe999\"' >> ~/.config/ntfy/ntfy.yml
        "
      args:
        creates: "/home/azuser/.local/bin/ntfy"

    - name: "Download azcopy"
      become: true
      ansible.builtin.shell: |
        wget -O azcopy_v10.tar.gz https://aka.ms/downloadazcopy-v10-linux && tar -xf azcopy_v10.tar.gz --strip-components=1
        mv azcopy /usr/bin/
        chown root:root /usr/bin/azcopy
        chmod 755 /usr/bin/azcopy
        rm -rf azcopy_v10.tar.gz
      args:
        creates: "/usr/bin/azcopy"

    - name: "Login to azcopy"
      ansible.builtin.command: "azcopy login --identity"

    - name: "Setup SSH (if necessary)"
      register: "result"
      retries: 20
      delay: 5
      until: result is not failed
      ansible.builtin.script: "setup_ssh.sh"
      args:
        creates: "/home/azuser/.ssh/id_rsa"
