---
- name: "Setup Control VM"
  hosts: "all"
  gather_facts: false

  tasks:

    - name: "Gather selected facts"
      ansible.builtin.setup:
        filter:
          - 'ansible_date_time'

    - name: "Install azure-cli"
      become: true
      ansible.builtin.script: "setup_azure_cli.sh"
      args:
        creates: "/usr/bin/az"

    - name: "azure-cli login"
      ansible.builtin.command: "az login --identity"

    - name: "Setup jaz (if necessary)"
      ansible.builtin.script: "setup_jaz.sh"
      args:
        creates: "/home/azuser/.local/bin/jaz"

    - name: "git clone provisioning (if necessary)"
      ansible.builtin.git:
        repo: "http://github.com/azpos/provisioning"
        dest: "/home/azuser/provisioning"
        clone: true
        update: true

    - name: "Send notification"
      ansible.builtin.command: "/home/azuser/.local/bin/ntfy send 'Provisioning of CONTROL finished: {{ ansible_date_time.iso8601 }}'"
