---
- name: "Setup Control VM"
  hosts: "all"
  gather_facts: false

  tasks:
    - name: "Install azure-cli"
      become: true
      ansible.builtin.script: "setup_azure_cli.sh"
      args:
        creates: "/usr/bin/az"

    - name: "azure-cli login"
      ansible.builtin.command: "az login --identity"

    - name: "Setup jaz (if necessary)"
      ansible.builtin.script: "setup_jaz.sh"
      args:
        creates: "/home/azuser/.local/bin/jaz"

    - name: "git clone provisioning "
      ansible.builtin.git:
        repo: "https://foosball.example.org/path/to/repo.git"
        dest: "/home/azuser/provisioning"

    - name: "Send notification"
      ansible.builtin.command: "/home/azuser/.local/bin/ntfy send 'Provisioning of CONTROL finished: {{ ansible_date_time.iso8601 }}'"
