---
- name: "Setup Control VM"
  hosts: "all"
  gather_facts: false

  tasks:

    - name: "Install dependencies"
      become: true
      ansible.builtin.apt:
        pkg:
          - "libgl1"
          - "libxcursor1"
          - "libxft-dev"
          - "libxinerama1"
        state: "present"
        update_cache: true
        install_recommends: false
        lock_timeout: 60
        cache_valid_time: 3600

    - name: "Install azure-cli"
      become: true
      ansible.builtin.script: "setup_azure_cli.sh"
      args:
        creates: "/usr/bin/az"

    - name: "azure-cli login"
      ansible.builtin.command: "az login --identity"

    - name: "Setup jaz (if necessary)"
      ansible.builtin.script: "setup_jaz.sh"
      args:
        creates: "/home/azuser/.local/bin/jaz"

    - name: "git clone provisioning (if necessary)"
      ansible.builtin.git:
        repo: "http://github.com/azpos/provisioning"
        dest: "/home/azuser/provisioning"
        clone: true
        update: true

    - name: "git clone pyposeidon (if necessary)"
      ansible.builtin.git:
        repo: "http://github.com/ec-jrc/pyPoseidon"
        dest: "/home/azuser/pyPoseidon"
        clone: true
        update: true

    - name: "Setup poetry (if necessary)"
      become: false
      ansible.builtin.shell: |
        /usr/bin/bash -lic '
          python3.10 -m pipx install poetry
          python3.10 -m pipx inject poetry poetry-dynamic-versioning
          mkdir -p /mnt/cache/poetry/
          poetry config cache-dir /mnt/cache/poetry/
        '
      args:
        creates: "/home/azuser/.local/bin/poetry"

    - name: "Create seareport_env"
      ansible.builtin.shell: |
        /usr/bin/bash -lic '
        source init_conda
        wget -O /tmp/binary.lock https://raw.githubusercontent.com/ec-jrc/pyPoseidon/master/locks/conda-ubuntu-latest-binary-p3.10.lock
        micromamba create -n seareport_env -f /tmp/binary.lock
        micromamba activate seareport_env
        rm -rf /tmp/binary.lock
        '
      args:
        creates: "/mnt/micromamba/envs/seareport_env"

    - name: "Install python dependencies in seareport_env "
      ansible.builtin.shell: |
        /usr/bin/bash -lic '
        source init_conda
        micromamba activate seareport_env
        cd /home/azuser/provisioning
        poetry install
        '

    - name: "Send notification"
      ansible.builtin.command: "/home/azuser/.local/bin/ntfy send 'Provisioning of CONTROL finished: {{ now(utc=True) }}'"
