---
- name: "Setup Master VM"
  hosts: "master"
  gather_facts: false

  tasks:
    - name: "Update /etc/idmapd.conf"
      become: true
      ansible.builtin.replace:
        path: "/etc/idmapd.conf"
        regexp: "(nobody|nogroup)"
        replace: "azuser"

    - name: "Create /scratch/shared"
      become: true
      ansible.builtin.file:
        path: "/scratch/shared"
        state: "directory"
        mode: "0755"
        owner: "azuser"
        group: "azuser"

    - name: "Update /etc/exports"
      become: true
      ansible.builtin.lineinfile:
        path: "/etc/exports"
        line: "/scratch/shared    10.10.0.0/16(rw,sync,no_subtree_check)"
        create: false

    - name: "Update exportfs"
      become: true
      ansible.builtin.command: "exportfs -arv"

    - name: "Restart nfs-kernel-server"
      become: true
      ansible.builtin.systemd:
        state: "restarted"
        name: "nfs-kernel-server"
