---
- name: "Unmount NFS"
  hosts: "control,workers"
  gather_facts: false

  tasks:

    - name: "Unmount NFS volume"
      become: true
      ansible.posix.mount:
        path: "/scratch/shared"
        state: "unmounted"
      async: 60
      poll: 5
