---
- name: "Setup Worker VM"
  hosts: "workers"
  gather_facts: false

  tasks:
    - name: "Create /scratch/shared"
      become: true
      ansible.builtin.file:
        path: "/scratch/shared"
        state: "directory"
        mode: "0755"
        owner: "azuser"
        group: "azuser"

    - name: "Mount NFS volume"
      become: true
      ansible.posix.mount:
        src: "10.10.0.5:/scratch/shared"
        path: "/scratch/shared"
        opts: "rw,sync,hard"
        state: "mounted"
        fstype: "nfs"

    - name: "Install schism"
      ansible.builtin.script: "setup_schism.sh"
      args:
        creates: "/mnt/mambaforge/condabin/mamba"

    - name: "Sent notification"
      ansible.builtin.command: "/home/azuser/.local/bin/ntfy send 'Provisioning of WORKER finished: {{ ansible_date_time.iso8601 }}'"
